### ISSUE TITLE
update account 

### ISSUE THREAD

**Issue by nxmz** [Sadyyn/ReBomb2#19]

**Comment by nxmz** [comment]
Don't steal the money from others:)

**Comment by Sadyyn** [comment]
> Don't steal the money from others:)

How is putting a donate button on my program a scam? It's literally free and people can use it without paying anything. If people WANT to donate, they can. You're obviously stupid or don't know what the word "scam" or "steal" means.

**Comment by nxmz** [comment]
Is not donate when you ask money in instagram and say selling tool and after take the money don't answer you don't ask for donations you say i sell tools Don't be (cheap) *_*

**Comment by Sadyyn** [comment]
> Is not donate when you ask money in instagram and say selling tool and after take the money don't answer you don't ask for donations you say i sell tools Don't be (cheap) *_*

What the hell are you even talking about? I never even mentioned this product on Instagram or mentioned the word "selling". Show me the proof where I said I sell tools. You must've ran into a fake account of me.

**Comment by Sadyyn** [comment]
> Is not donate when you ask money in instagram and say selling tool and after take the money don't answer you don't ask for donations you say i sell tools Don't be (cheap) *_*

I'm waiting

**Comment by Sadyyn** [comment]
> Is not donate when you ask money in instagram and say selling tool and after take the money don't answer you don't ask for donations you say i sell tools Don't be (cheap) *_*

Not to mention, why would you buy a tool of mine when you're literally on the page where you can download it FOR FREE?!

WHOOSH

**Comment by nxmz** [comment]
hhhhhh Ok any one need a proof in my telegram : @H3H3F

**Comment by nxmz** [comment]
and is not fake account it's yours you put in you profile (instagram)

**Comment by Sadyyn** [comment]
> hhhhhh Ok any one need a proof in my telegram : @H3H3F

Post the proof right here so you can make a fool of yourself. No one is going to go to your telegram so you can scam them, stupid. Post it here.

**Comment by nxmz** [comment]
I can't share photo here and stop scammed people:)

**Comment by Sadyyn** [comment]
> I can't share photo here and stop scammed people:) 

There's literally an option to post photos here, you complete dullard.

**Comment by Sadyyn** [comment]
> I can't share photo here and stop scammed people:) 

Just like this. So post the photo ![anY1njE_460s.jpg](https://github.com/Sadyyn/ReBomb2/assets/73670067/03df855f-f11e-45b8-af87-680406f6a4a3)

**Comment by Sadyyn** [comment]
> I can't share photo here and i don't ask money like you in instagram and telegram I'm not cheap like you 😂 

You can't share the photo because you have no photo. I literally just posted a photo and so can you. Nothing else you say matters until you post proof. In the meantime, I will leave this up so everyone can laugh at what a complete and utter waste of life you are.

**Comment by nxmz** [comment]
![image](https://github.com/Sadyyn/ReBomb2/assets/21256065/f1848b8f-bb67-4365-9229-e009030ea5bb) 



Ok who is the scammer now? 😂

**Comment by nxmz** [comment]
![image](https://github.com/Sadyyn/ReBomb2/assets/21256065/9b342d94-68e3-4bca-b0cf-4375f59d1cf9)

everyone can laugh 😆

**Comment by Sadyyn** [comment]
> ![image](https://github.com/Sadyyn/ReBomb2/assets/21256065/989dc2e7-2f3e-489a-9797-d6bc8e8dfc72)
> 
> ![image](https://github.com/Sadyyn/ReBomb2/assets/21256065/0b131e9f-c4cf-4cc9-aa7e-995a2b825610)
> 
> ![image](https://github.com/Sadyyn/ReBomb2/assets/21256065/4b503bb8-e494-4807-bf0d-ae8bb46d123f)

This is my account, dude. I changed my URL a long time ago. But at least I know someone has a fake account of me now

https://instagram.com/biorat1?igshid=MzNlNGNkZWQ4Mg==

**Comment by Sadyyn** [comment]
> ![image](https://github.com/Sadyyn/ReBomb2/assets/21256065/c9b4e79c-92af-4c4f-b54d-e2f2189b49ca)
> 
> Are you changing your account and the same in your profile? 🙃 

Of course I am since it's not me. I never update this shit, dude. I didn't even expect it to have that many downloads so I just left old stuff up. Now, my name used to be B1orat with that in the URL, yes but I changed it to BioRat like months ago. But now I know there's a scammer I have to deal with.... Fuck.

**Comment by Sadyyn** [comment]
> ![image](https://github.com/Sadyyn/ReBomb2/assets/21256065/c9b4e79c-92af-4c4f-b54d-e2f2189b49ca)
> 
> Are you changing your account and the same in your profile? 🙃 

And for anyone wondering, I have proof of people offering to pay me for this since 2022 and me turning them down. I turn them down because there's no guarantee that this will even work so I would never charge anyone to use it. I didn't even think you people would download this thing

![Screenshot_20230706-123243_Instagram.jpg](https://github.com/Sadyyn/ReBomb2/assets/73670067/d6c114f0-334d-4cc3-b691-d2cda17efdaa)

**Comment by nxmz** [comment]
bro I'm sorry for that and please find a way to close his account I don't need the money but i want to share this scammer and your work it's very good

**Comment by Sadyyn** [comment]
> bro I'm sorry for that and please find a way to close his account I don't need the money but i want to share this scammer and your work it's very good 

Thank you, bro. I'm so fucking sorry this happened to you and I'm sorry I came at you defensively. I'm still shocked. I've never had a fake profile made of me.

Thank you so much for bringing this to my attention. The fake account is being delt with
